### ISSUE TITLE
Packege "lcm2ros" missing

### ISSUE THREAD

**Issue by zwqnju** [zq7734509/qt_bag_segment#1]
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "lcm2ros" with any
  of the following names:

    lcm2rosConfig.cmake
    lcm2ros-config.cmake

  Add the installation prefix of "lcm2ros" to CMAKE_PREFIX_PATH or set
  "lcm2ros_DIR" to a directory containing one of the above files.  If
  "lcm2ros" provides a separate development package or SDK, be sure it has
  been installed.

How can I fix this?

**Comment by zq7734509** [comment]
The lcm2ros is a custom package that transform the lcm format data into rosmsg, it is mainly used in the auto drive projects, you can just remove it from the CMakelists.txt and remove the msg type of it in the src codes.

**Comment by zwqnju** [comment]
Thanks. I have run your code successfully. FYI, "catkin_package()" is missing in your CMakeLists.txt. There will not be any executable file without this line of code.
